android: PLATFORM=android -r features/support -r features/som/android -r features/step_definitions -r features/android
ios: PLATFORM=ios -r features/support -r features/ios -r features/som/ios -r features/step_definitions